### ISSUE TITLE
这个项目中有大量的汇编代码？

### ISSUE THREAD

**Issue by RouderSky** [CallMeZhou/Puresoft3D#10]

**Comment by CallMeZhou** [comment]
嗯……这是一个“issue”？:-)  是的，包含不少x86汇编代码，不过仔细看会发现那些汇编程序并没有复杂的逻辑，只是实现一些基于SIMD指令的数学运算例程。由于这是一个“模拟显卡”的软件渲染程序，所以我希望它能够渲染所谓的“交互式三维图形”，说白了就是让观察者能够在场景里随便走走到处看看。因此需要尽量挖掘通用CPU的处理能力，这包括基于超线程多核的并行计算，以及SIMD指令。

**Comment by HTWER** [comment]
大致了解，谢谢大神
