### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by Too-Naive** [CallMeZhou/Puresoft3D#6]
![image](https://cloud.githubusercontent.com/assets/16496671/15354498/80a7d924-1d20-11e6-9bf7-a8f65810eb77.png)

**Comment by CallMeZhou** [comment]
哈哈～爱你～～

**Comment by Too-Naive** [comment]
现在的年轻人 动不动就说爱别人
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by CallMeZhou** [comment]
我才是一副见了鬼的样子好不？快40了被人说成现在的年轻人:-D
![一副见了鬼的样子](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by Too-Naive** [comment]
40了还随随便便爱别人 太污了
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by CallMeZhou** [comment]
![一副见了鬼的样子](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)

**Comment by Too-Naive** [comment]
羞羞脸
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)
